### ISSUE TITLE
Error while initializing solution on PTC.ComponentManagement.EntryPoint

### ISSUE THREAD

**Issue by AlexandreSalmon9a** [PTCInc/twx-solution-framework#2]
Hello there!

I noticed that when using the InitializeSolution() service more than once, it throws an error on PTC.ComponentManagement.

It seems the culprit is in the DeployComponent() service on PTC.ComponentManagement.EntryPoint_TT. 

Could you maybe add a Try/Catch around lines 18-20:

```js
Things["PTC.ComponentManagement.PackageExportFileRepo"].CreateFolder({
	path: "/Packages/" /* STRING */
});
```
If the folder exists, it marks the BB in Error, and the error message states that the "file already exists". If the folder to be created is deleted, it initializes ok though.

Thank you for your work,

Regards, 

Alexandre

**Comment by mvulcano-ptc** [comment]
Quite a bit delayed on this, but this issue has been resolved. I can't remember if it was in this latest version, or in the 9.5.3 release, but a Try/Catch was added around this section of code in the PTC.ComponentManagement.DeployComponent service: 
![image](https://github.com/PTCInc/twx-solution-framework/assets/90467480/b7853724-3dc8-49d9-86b7-9df8362815ec)

**Comment by mvulcano-ptc** [comment]
Closing issue as resolved.
